<?php
namespace App\Controller;

use Cake\Event\Event;
use App\Controller\AppController;
use Cake\Utility\Inflector;

/**
 * Threads Controller
 *
 * @property \App\Model\Table\ThreadsTable $Threads
 *
 * @method \App\Model\Entity\Thread[] paginate($object = null, array $settings = [])
 */
class ThreadsController extends AppController
{

    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub

        $this->Auth->allow([
            'index',
            'discussion'
        ]);
    }

    /**
     * Index method
     *
     * @return \Cake\Http\Response|void
     */
    public function index()
    {
        $threads = $this->paginate($this->Threads);

        $this->set(compact('threads'));
    }

    /**
     * View method
     *
     * @param string|null $id Thread id.
     * @return \Cake\Http\Response|void
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function discussion($nodeId, $slug)
    {
        $this->loadModel('Nodes');

        $node = $this->Nodes->get($nodeId);

        $firstPost = $this->Threads->findBySlug($slug)->first();

        $threadQuery = $this->Threads->findBySlug($slug, [
            'contain' => ['Nodes']
        ]);

        $thread = $this->paginate($threadQuery);

        $this->set(compact('thread', 'node', 'firstPost'));
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $thread = $this->Threads->newEntity();

        if ($this->request->is('post'))
        {
            $thread->slug = Inflector::slug($this->request->getData('title'));

            $thread = $this->Threads->patchEntity($thread, $this->request->getData());

            if ($this->Threads->save($thread))
            {
                $this->Flash->success(__('The thread has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The thread could not be saved. Please, try again.'));
        }

        $threads = $this->Threads->Threads->find('list', ['limit' => 200]);
        $nodes = $this->Threads->Nodes->find('list', ['limit' => 200]);
        $this->set(compact('thread', 'threads', 'nodes'));
        $this->set('_serialize', ['thread']);
    }

    /**
     * Edit method
     *
     * @param string|null $id Thread id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $thread = $this->Threads->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $thread = $this->Threads->patchEntity($thread, $this->request->getData());
            if ($this->Threads->save($thread)) {
                $this->Flash->success(__('The thread has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The thread could not be saved. Please, try again.'));
        }
        $threads = $this->Threads->Threads->find('list', ['limit' => 200]);
        $nodes = $this->Threads->Nodes->find('list', ['limit' => 200]);
        $users = $this->Threads->Users->find('list', ['limit' => 200]);
        $this->set(compact('thread', 'threads', 'nodes', 'users'));
        $this->set('_serialize', ['thread']);
    }

    /**
     * Delete method
     *
     * @param string|null $id Thread id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $thread = $this->Threads->get($id);
        if ($this->Threads->delete($thread)) {
            $this->Flash->success(__('The thread has been deleted.'));
        } else {
            $this->Flash->error(__('The thread could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }
}
